export default {
  type: 'PUBLIC_NETWORK',
  serviceTypeId: 'NETWORK',
  treeKey: 'p-17',
  label: 'public',
  status: 'ACTIVE',
  children: [
    {
      type: 'ROUTER',
      serviceTypeId: 'NETWORK',
      treeKey: 'r-16',
      label: 'route#2',
      status: 'ACTIVE',
      children: [
        {
          type: 'NETWORK',
          serviceTypeId: 'NETWORK',
          treeKey: 'n-21',
          label: 'Network#1',
          status: 'ACTIVE',
          children: [
            {
              objId: 21517,
              type: 'SERVER',
              objtypeId: 'VIRTUALSVR',
              platformId: 30,
              serviceTypeId: 'SERVER',
              treeKey: 's-30',
              label: 'Server_Cirros#2',
              objName: 'Server_Cirros#2',
              ipaddress: '172.16.255.20',
              objDefineId: 'CLOUD_SERVICE',
              objManagetypeId: 'CMS',
              eventlevelId: 'MN',
              children: [],
              rscInfos: [
                {
                  rsctypeId: 'SVR_CPU',
                  rscId: 'CPU_USERATE',
                  rscUnit: '%',
                  hashkeyId: 3908215154976729600,
                  hashkeyIdString: '3908215154976729588',
                },
                {
                  rsctypeId: 'SVR_STATUS',
                  rscId: 'VSERVER_STATUS',
                  rscUnit: '',
                  hashkeyId: -4385482943103909400,
                  hashkeyIdString: '-4385482943103909186',
                },
              ],
              cmpObjId: 22,
              createDatetime: 1674805362000,
              serviceSubTypeId: 'SERVER',
              serviceSubTypeName: '서버',
              publicIp: '172.16.124.236',
              privateIp: '172.16.255.20',
              projectId: 5,
              openstackProjectId: 24,
              iaasPlatformType: 'OPENSTACK',
              networkId: 21,
              zoneName: 'nova',
              loadBalancerId: 4,
              serverId: 30,
              serverName: 'Server_Cirros#2',
              vcpu: 1,
              memory: 2097152,
              disk: 5242880,
              imageName: 'watchall-cmp-Cirros_5.2_app',
            },
          ],
          cmpObjId: 17,
          createDatetime: 1674789214000,
          serviceSubTypeId: 'NETWORK',
          serviceSubTypeName: '네트워크',
          projectId: 5,
          routerId: 16,
          networkId: 21,
          networkName: 'Network#1',
          cidr: '172.16.255.0/24',
          typeNetworkId: 21,
          externalRouter: 'N',
          zoneName: 'nova',
          deviceCount: 7,
        },
      ],
      cmpObjId: 18,
      createDatetime: 1674790269000,
      serviceSubTypeId: 'ROUTER',
      serviceSubTypeName: '라우터',
      projectId: 5,
      publicNetworkId: 17,
      publicNetworkName: 'public',
      routerId: 16,
      routerName: 'route#2',
      networkCount: 1,
      zoneName: 'nova',
    },
  ],
  serviceSubTypeId: 'NETWORK',
  serviceSubTypeName: '네트워크',
  publicNetworkId: 17,
  routerCount: 1,
  networkName: 'public',
  cidr: '172.16.0.0/16',
  zoneName: 'nova',
};
